### ISSUE TITLE
Support the --path parameter when calling `pip list`

### ISSUE THREAD

**Issue by westonsteimel** [di/pip-api#111]
From what I can tell the `--path` parameter was added to `pip list` in [19.2](https://pip.pypa.io/en/stable/news/#id487)

I was hoping to get [pip-audit](https://github.com/trailofbits/pip-audit) to support passing in a specific directory to audit (such as when `pip install --target` is used), but I suspect a change will be needed here first, possibly somewhere in: https://github.com/di/pip-api/blob/b3686289955c6be75d7a4021dd133f3764f5a1c9/pip_api/_installed_distributions.py#L59

**Comment by di** [comment]
@woodruffw @tetsuo-cpp, could you take a look here?
