### ISSUE TITLE
Add a `conda` installation option for `pip-api`

### ISSUE THREAD

**Issue by sugatoray** [di/pip-api#116]
Adding a conda installation option could be helpful. I have started working on this already to make `pip-audit` available on `conda-forge` channel. Once the conda-forge :bulb: [**PR**](https://github.com/conda-forge/staged-recipes/pull/17235) gets merged, I will push a PR in this repository to update the install-instructions in the readme. 

```sh
conda install -c conda-forge pip-api
```

- **Current status**: All CI's passed. Awaiting review/merger. https://github.com/conda-forge/staged-recipes/pull/17235
- **Note**: The PR is being used to add `pip-api` and `pip-audit` to conda-forge.

**Comment by di** [comment]
Hi @sugatoray, any update here?

**Comment by sugatoray** [comment]
Yes. `pip-api` is available on conda-forge now. 🚀

**Comment by sugatoray** [comment]
Hello @di, 

Would you like to be a co-maintainer of the conda-forge feedstock?

This will help you in keeping both PyPI and conda-forge releases upto date.

**Comment by di** [comment]
No thanks! 🙂
