### ISSUE TITLE
git tags missing since version 0.2.4

### ISSUE THREAD

**Issue by hardfalcon** [di/pip-api#139]
Hi, I've noticed the git tags are missing for versions >= 0.0.24. This makes packaging distro packages slightly more complicated because it prevents people from using "predictable" Github URLs for downloading the source code tarball, and instead requires either the use of non-predictable download URLs from pypi.org or figuring out by hand which git commit id corresponds to which version. So would it be possible to add the missing git tags? :)

**Comment by di** [comment]
Fixed: https://github.com/di/pip-api/tags
