### ISSUE TITLE
installed_distributions() always uses python 2 executable

### ISSUE THREAD

**Issue by jpstotz** [di/pip-api#15]
When you execute `installed_distributions()` pip_api performs a python call to list the installed packages. 

The used python executable is hard coded to `python` (if the environment variable `PIPAPI_PYTHON_LOCATION` is not set). It would be better to check here if the script is executed via python 2 or 3 and then use `python` respectively `python3` depending on the used Python version. 

Or alternatively simply use the current python interpreter executable (stored in the variable `sys.executable`)

**Comment by di** [comment]
Thanks for the report @jpstotz! This is fixed in [`pip-api==0.0.4`](https://pypi.org/project/pip-api/0.0.4/).

As an aside, I'm curious what you're using this project for, and how you found it, if you have a second to let me know. Thanks!
