### ISSUE TITLE
Switch to `pyproject.toml` for the project build?

### ISSUE THREAD

**Issue by woodruffw** [di/pip-api#155]
`pip-api` is a pure Python package, so switching it fully over to `pyproject.toml` (the way we've done for `pip-audit` and `sigstore-python`) should be pretty straightforward.

**Comment by di** [comment]
Sounds good to me!

**Comment by woodruffw** [comment]
Cool! Should be very quick to do, so I'll stamp it out now 🙂

**Comment by woodruffw** [comment]
#156
