### ISSUE TITLE
Remove slogan to prevent confusion

### ISSUE THREAD

**Issue by jezdez** [di/pip-api#17]
Hi @di, could you please remove the slogan "The official unofficial pip API." to reduce the chance for creating confusion whether to base packaging tools on this?

As you know pip doesn't support an API for a good reason (maintainer sanity mostly) and it's a disservice to the community to create the impression that you personally can provide that API long-term. I get the joke of the slogan of course, and I snickered a bit, but then I thought about the possible downsides in the future. Let's not risk making things more complicated just for the sake of snark :)

Rest assured your efforts to release this 3rd-party library is not in question, in fact I really appreciate that you've done so. So thank you!

**Comment by di** [comment]
Excellent point, thank you for raising it. Done!
