### ISSUE TITLE
Search Functionality

### ISSUE THREAD

**Issue by kgrvamsi** [di/pip-api#2]
@di Do we have a search functionality to check if a package exists?

**Comment by di** [comment]
Hi @kgrvamsi, not sure exactly what you mean. Do you mean something like `pip search`?

**Comment by kgrvamsi** [comment]
Right @di sorry i thought i mentioned the command but yes we `pip search`

**Comment by di** [comment]
@kgrvamsi PyPI provides an [XML-RPC API](https://warehouse.readthedocs.io/api-reference/xml-rpc/) which `pip search` uses under the hood, you probably just want to interact with that API directly.

**Comment by kgrvamsi** [comment]
Awesome @di this helps.
