### ISSUE TITLE
Python 3.4 support dropped

### ISSUE THREAD

**Issue by jayvdb** [di/pip-api#28]
https://github.com/di/pip-api/commit/07531fafa49486a8fdf4145db5bacd69bd1e5f67 dropped support for Python 3.4, and thus the same has happened in `pytest-reqs` (or maybe it was the other way around).

However there appears to be no incompatibilities with Python 3.4 in the code base.  Reverting that commit here results in a green build still.

What was the reason for it?  My guess is because it is EOL by Python Foundation.

This is probably a deal-breaker for coala, as it will break our minimum support for python 3.4.2, which is predicated around a travis CI requirements more so than a user requirement, and will also break our support for several LTS releases of distros which were using Python 3.4, such as Debian 8 (jessie) which has EOL June 30, 2020 -- a year away, and openSUSE 15.0, EOL November 2019.

We could play some tricks to make pytest-reqs optional so it isnt used on older versions of pytest, if that was truly necessary.  Irony alert -- we would probably need https://github.com/di/pytest-reqs/pull/33 merged for that to be possible.

**Comment by di** [comment]
Sorry about that. Yes, I dropped it because it is past EOL, but adding the `python_requires` field might have been premature. I'd be amenable to making `pip-api` installable for 3.4, but I'm not planning to explicitly support or test against 3.4 any more.

**Comment by jayvdb** [comment]
What about having a very reduced test matrix for py34, here and for pytesg-reqs? E.g. only test one stable version of pip, and allow jt to fail?

**Comment by di** [comment]
Sure, that would help me determine when `python_requires` should actually be added back.
