### ISSUE TITLE
test_parse_requirements_editable_file requires packaging 19.0

### ISSUE THREAD

**Issue by jayvdb** [di/pip-api#30]
Recently added `test_parse_requirements_editable_file` requires packaging 19.0 , which wasn't updated in setup.py

See https://travis-ci.org/jayvdb/pip-api/jobs/533291247

There should be a tox factor for the minimum `packaging` version here and at pytest-reqs, so these problems are identified during development.

I dont believe it is acceptable for pip-api to require packaging 19.0 at this stage.  It would be a very strange python env that has pip 6.0 and packaging 19.0 together.

IMO, it should be acceptable to have a version of `packaging` roughly equivalent to the version which was vendored by the supported pip version.

As a result, I think pip-api tests need to skip when features are not supported by the runtime version of packaging, or vendor the needed version of packaging.

**Comment by di** [comment]
I think I'd prefer to vendor in `packaging` here.

**Comment by jayvdb** [comment]
That means also vendoring its deps attrs, pyparsing & six.
