### ISSUE TITLE
Make requirements and distributions case insensitive

### ISSUE THREAD

**Issue by malikoth** [di/pip-api#36]
In doing some research before writing this ticket, I learned that the `django` project on PyPI actually lists its project name as "Django" with a capitol "D".  I've always just typed the all lowercase version into a `requirements.txt` or `pip install` command.  Turns out that either is fine, per [PEP 426](https://www.python.org/dev/peps/pep-0426/#name)

> All comparisons of distribution names MUST be case insensitive, and MUST consider hyphens and underscores to be equivalent.

What I'm currently working towards is making an `is_environment_up_to_date` function, in which I need to look over the keys in the dict I got back from `pip_api.parse_requirements`, and see if they're all present in the dict I got back from `pip_api.installed_distributions`.  The fact that putting "django" as a line in "requirements.txt" and having `pip_api` tell me that that item wasn't installed threw me for a loop for a minute.

Certainly I could solve my problem by just capitalizing the first letter of that line.  However, I'd love to see this project get "better" (according to me) by more closely following relevant PEPs.  I propose that both of the aforementioned functions `pip_api.parse_requirements` and `pip_api.installed_distributions` no longer return a plain dict object, but a dict-subclass that is case insensitive, like [this one](https://stackoverflow.com/a/51083318).  Then if I have `django` in my `requirements.txt`, and `Django` is installed (thanks whoever made that weird, arbitrary, and unpythonic decision for Django!), then this code:

```
reqs = pip_api.parse_requirements('requirements.txt')
deps = pip_api.installed_distributions()
assert all(req in deps for req in reqs.keys())
```
will succeed.

If you agree with my proposal, I'll happily submit a PR.  :)

**Comment by di** [comment]
The current behavior of `parse_requirements` and `installed_distributions` (i.e., not canonicalizing the project name) is likely because they are mimicking the same behavior of the internal `pip` APIs they are designed to replace. I can't recall whether this is actually true, but I'm fairly sure it is. If so, this would potentially be a breaking change for users who expect case-sensitive behavior.

So I'd say it's the user's responsibility to canonicalize the project name (specifically via [`packaging.utils.canonicalize_name`](https://packaging.pypa.io/en/latest/utils/#packaging.utils.canonicalize_name)), not `pip-api`'s responsibility.

By the way, it's not just case sensitivity: `pip-api`, `pip_api` and `pip.api` are all equivalent project names.

**Comment by malikoth** [comment]
Thanks for the link to `canonicalize_name`, I didn't know that was there.  I'll use that, and that'll get me going just fine.

I saw, as per the pep I linked above, that hyphens and underscores were to be treated as identical (which I was going to take into account when I implemented my idea if you approved it), but is there something documented somewhere that says periods belong to that group as well?  I mean, I see that [pip is doing it too](https://github.com/pypa/pip/blob/169eebdb6e36a31e545804228cad94902a1ec8e9/src/pip/_vendor/packaging/utils.py#L11) so...  Anyways, this is just out of curiosity.

Pip does canonicalize the name.  [In some places](https://github.com/pypa/pip/search?q=canonicalize_name).  Obviously not everywhere, or `pip list` would show `django`.  The question is, does it do so .....?  Actually, I don't even know enough at this point to finish asking that question.  I certainly wouldn't want to make a backwards-incompatible change though, so it seems this issue should be closed.  That's too bad though -- I was getting excited about implementing this.  :P

**Comment by di** [comment]
> I saw, as per the pep I linked above, that hyphens and underscores were to be treated as identical (which I was going to take into account when I implemented my idea if you approved it), but is there something documented somewhere that says periods belong to that group as well? I mean, I see that pip is doing it too so... Anyways, this is just out of curiosity.

Yeah, I'm actually surprised that the PEP doesn't mention periods in that line, it might have been an oversight and should be corrected.

I think I'll close this but we can revisit if necessary. There's plenty of other things to implement :)
