### ISSUE TITLE
pip-api should require `six`

### ISSUE THREAD

**Issue by glasserc** [di/pip-api#42]
This package uses `six` in https://github.com/di/pip-api/blob/master/pip_api/_vendor/packaging/requirements.py#L12, but doesn't declare it in `setup.py`. Most environments install `six` somewhere or another, but it's possible not to, which will make importing `pip_api` fail.

**Comment by di** [comment]
Thanks! Fixed in https://pypi.org/project/pip-api/0.0.13/
