### ISSUE TITLE
'parse_requirements' does not consider environment markers

### ISSUE THREAD

**Issue by hexagonrecursion** [di/pip-api#61]
Trying to parse the following file
```
pytest>=4.6.10,<5 ; python_version < '3'
pytest>=5.4.2,<6 ; python_version >= '3'
```
Throws an exception
```
PipError: Double requirement given: pytest<6,>=5.4.2 (already in pytest<5,>=4.6.10, name='pytest')
```

**Comment by di** [comment]
This is because `parse_requirements` is not considering environment markers. This library would need go do something similar to `pip` here: https://github.com/pypa/pip/blob/faee60baea2b850427b5fceb22383883fa11290b/src/pip/_internal/req/req_set.py#L90-L95

**Comment by woodruffw** [comment]
cc @tetsuo-cpp could you take a look at this? I think the `Requirements` class gives us everything we need, we just need to dedupe the requirements based on which one(s) satisfy the environment marker(s): https://github.com/di/pip-api/blob/98d3aa8554159a0b32677f0623f951e7170b1fd8/pip_api/_vendor/packaging/requirements.py#L82

**Comment by di** [comment]
Yes, `packaging.markers` should be sufficient here (and also what `pip` uses).

**Comment by tetsuo-cpp** [comment]
I think the code to use the marker is relatively straight forward (we just check `marker.evaluate()` prior to inserting the requirement into the dict). The problem I'm seeing is that the marker isn't being parsed properly and is being set to `None` when we construct the `packaging.Requirement`.

I'm looking at the parsing code to figure out what's going wrong here.
