### ISSUE TITLE
test failure

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [di/pip-api#81]
tests fails with
```
========================================================================================================= short test summary info ==========================================================================================================
ERROR tests/test_installed_distributions.py::test_installed_distributions - AttributeError: module 'virtualenv' has no attribute 'create_environment'
ERROR tests/test_tests.py::test_isolation[True] - AttributeError: module 'virtualenv' has no attribute 'create_environment'
ERROR tests/test_tests.py::test_isolation[False] - AttributeError: module 'virtualenv' has no attribute 'create_environment'
ERROR tests/test_tests.py::test_all_the_right_pips - AttributeError: module 'virtualenv' has no attribute 'create_environment'
```

virtualenv is version 20.4.7

**Comment by di** [comment]
Hi, can you give me some more details about how you're running the test suite? E.g. if you're using `tox`, what version? What version of Python and `pip`? What platform are you on?

It's not clear to me why this would be failing, as the test suite doesn't directly call `create_environment` anywhere. In additon, the full suite run ran 3 days ago with virtualenv 20.4.7 and had no issues: https://github.com/di/pip-api/runs/2923642539

**Comment by Alessandro-Barbieri** [comment]
Full log here: https://gist.github.com/3b8dcb7f3afee58bfdc311a275d1aa10
I'm packaging pip-api for the gentoo overlay guru.

Python version doesn't matter, it fail with every python (pypy3, 7, 8, 9, 10)
`platform linux -- Python 3.7.10[pypy-7.3.4-final], pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /usr/bin/pypy3`

```
______________________________________________________________________________________________ ERROR at setup of test_installed_distributions ______________________________________________________________________________________________

tmpdir = '/var/tmp/portage/dev-python/pip-api-0.0.14/temp/pytest-of-portage/pytest-0/test_installed_distributions0', isolate = None

    @pytest.yield_fixture
    def venv(tmpdir, isolate):
        """
        Return a virtual environment which is unique to each test function
        invocation created inside of a sub directory of the test function's
        temporary directory.
        """
        venv_location = os.path.join(str(tmpdir), "workspace", "venv")
>       venv = virtualenv.create_environment(venv_location)
E       AttributeError: module 'virtualenv' has no attribute 'create_environment'

isolate    = None
tmpdir     = '/var/tmp/portage/dev-python/pip-api-0.0.14/temp/pytest-of-portage/pytest-0/test_installed_distributions0'
venv_location = '/var/tmp/portage/dev-python/pip-api-0.0.14/temp/pytest-of-portage/pytest-0/test_installed_distributions0/workspace/venv'

tests/conftest.py:88: AttributeError
```

**Comment by di** [comment]
It looks like you're using an old version of this library with a version of `virtualenv` it didn't support. This was fixed in https://github.com/di/pip-api/commit/d7f5fc9f182ab99d3b84da253ff0584dc67cc6a2, and prior to that change it pinned `virtualenv<20` in the test suite, so this issue shouldn't be possible.

**Comment by Alessandro-Barbieri** [comment]
I'm using the latest tagged version 0.0.14

**Comment by di** [comment]
Still shouldn't be an issue with that tag, but I've gone ahead and pushed tags for 0.0.17 through 0.0.20 as well.
