### ISSUE TITLE
Use `pip list --format=json` when pip is sufficiently new?

### ISSUE THREAD

**Issue by woodruffw** [di/pip-api#92]
It looks like `pip` >= 9.0.0 also supports `--format=json`, which is probably more reliable than parsing the column output. Thoughts?

**Comment by di** [comment]
I can't recall at this point if there was a reason I chose `--format=columns`. I suspect both will be equally reliable but I wouldn't be opposed to switching to `--format=json` if they are equivalent.

FWIW, `pip-api` already differentiates between < and >= `9.0.0`:

https://github.com/di/pip-api/blob/e6305c0af25a3f638bab4233e45b3fc678a10e36/pip_api/_installed_distributions.py#L82-L85

**Comment by woodruffw** [comment]
> I can't recall at this point if there was a reason I chose --format=columns. I suspect both will be equally reliable but I wouldn't be opposed to switching to --format=json if they are equivalent.

Yep, from some local testing they look equivalent. Here's both run on a contrived environment:

```
$ pip list --format=columns
Package         Version
--------------- --------
appdirs         1.4.4
black           21.5b2
click           8.0.1
cmakelang       0.6.13
flake8          3.9.2
mccabe          0.6.1
mypy-extensions 0.4.3
pathspec        0.8.1
pip             21.1.2
pycodestyle     2.7.0
pyflakes        2.3.1
regex           2021.4.4
setuptools      49.2.1
six             1.16.0
toml            0.10.2
```

```
$ pip list --format=json | jq
[
  {
    "name": "appdirs",
    "version": "1.4.4"
  },
  {
    "name": "black",
    "version": "21.5b2"
  },
  {
    "name": "click",
    "version": "8.0.1"
  },
  {
    "name": "cmakelang",
    "version": "0.6.13"
  },
  {
    "name": "flake8",
    "version": "3.9.2"
  },
  {
    "name": "mccabe",
    "version": "0.6.1"
  },
  {
    "name": "mypy-extensions",
    "version": "0.4.3"
  },
  {
    "name": "pathspec",
    "version": "0.8.1"
  },
  {
    "name": "pip",
    "version": "21.1.2"
  },
  {
    "name": "pycodestyle",
    "version": "2.7.0"
  },
  {
    "name": "pyflakes",
    "version": "2.3.1"
  },
  {
    "name": "regex",
    "version": "2021.4.4"
  },
  {
    "name": "setuptools",
    "version": "49.2.1"
  },
  {
    "name": "six",
    "version": "1.16.0"
  },
  {
    "name": "toml",
    "version": "0.10.2"
  }
]
```

If the columnar format is sufficiently stable, then I see no reason to switch! My only thought there was that the JSON form is more defensive against small changes to `pip list`, e.g. them adding another header line 🙂

**Comment by di** [comment]
> My only thought there was that the JSON form is more defensive against small changes to `pip list`, e.g. them adding another header line

Agreed, although the test suite for this project should easily identify any subtle changes like that.

**Comment by woodruffw** [comment]
> Agreed, although the test suite for this project should easily identify any subtle changes like that.

Makes sense! Does the test suite include checks against `pip`'s current development/stable head? I can foresee an edge case where `pip-audit` calls into `pip_api`, which then shells out to a future version of `pip` that hasn't been added to the test matrix yet and has made a change to the columnar format. That would get caught by the time the next `pip` release is made, but in the mean time it would break every install of `pip-audit` until we push a version with a bumped dependency.

**Comment by di** [comment]
> Does the test suite include checks against `pip`'s current development/stable head?

It does not. A daily cron workflow that checks this across supported Python versions would probably be worthwhile to add.

**Comment by woodruffw** [comment]
Sounds good. I'll also go ahead with the JSON approach, since that'll also be defensive against that (unlikely) edge case.

**Comment by woodruffw** [comment]
Another thing I noticed: `pip list -v --format=json` produces even more detail, like so:

```json
  {
    "name": "appdirs",
    "version": "1.4.4",
    "location": "/Users/william/.pyenv/versions/3.9.4/lib/python3.9/site-packages",
    "installer": "pip"
  },
```

...so I'll use that to fill in the `location` as well. There's also the `installer` field, which could also be useful in the context of `pip-audit`, although that doesn't need to be addressed directly here.
