### ISSUE TITLE
Type hints?

### ISSUE THREAD

**Issue by woodruffw** [di/pip-api#96]
`pip-audit` is consuming `pip-api`, and is aiming for 100% MyPy coverage in the process.

`pip-api` currently doesn't have any type signatures, so we disable our MyPy checking wherever we `import pip_api`.

Is adding type signatures to the public APIs worth it here? If so, it's something we could dedicate engineering time to.

**Comment by di** [comment]
I think the public API here is simple enough that this shouldn't be hard to do, and would be beneficial for `pip-audit`. So yes, I think it's worth doing!
